name: Test Suite

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  change-detection:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      files_changed: ${{ steps.changed-udfs.outputs.files_any_changed }}
      public_changed: ${{ steps.changed-udfs.outputs.public_any_changed }}
      tests_changed: ${{ steps.changed-udfs.outputs.tests_any_changed }}
      public_files: ${{ steps.changed-udfs.outputs.public_all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all changed UDFs
        id: changed-udfs
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          separator: ","
          files_yaml: |
            public:
              - public/**
            files:
              - files/**
            tests:
              - tests/**

  files-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: change-detection
    if: github.event_name == 'push' || needs.change-detection.outputs.files_changed == 'true' || needs.change-detection.outputs.tests_changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: pip install fused[batch] pytest openpyxl duckdb fiona scipy

      - name: Run tests for files udfs
        shell: bash
        env:
          AUTH0_REFRESH_TOKEN: ${{ secrets.AUTH0_REFRESH_TOKEN }}
        run: pytest tests/test_file_udfs.py --tb=short

  public-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: change-detection
    if: github.event_name == 'push' || needs.change-detection.outputs.public_changed == 'true' || needs.change-detection.outputs.tests_changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: pip install fused[batch] pytest openpyxl duckdb fiona scipy

      - name: Run tests for public udfs
        env:
          AUTH0_REFRESH_TOKEN: ${{ secrets.AUTH0_REFRESH_TOKEN }}
          CHANGED_FILES: ${{ needs.change-detection.outputs.public_files }}
        shell: bash
        run: pytest tests/test_public_udfs.py --tb=short

  report-status:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [files-tests, public-tests]
    if: always()
    steps:
      - name: Report test status
        run: |
          echo "Files tests: ${{ needs.files-tests.result }}"
          echo "Public tests: ${{ needs.public-tests.result }}"

          if [ "${{ needs.files-tests.result }}" == "failure" ] || [ "${{ needs.public-tests.result }}" == "failure" ]; then
            # Overall workflow failure
            exit 1
          fi

          # tests passed or skipped

